theme: jekyll-theme-cayman

title: Open eClass Companion App
description: Made by Dimitris Gkoumas

links:
  githubprof: https://github.com/Jimminer
  playstore: https://play.google.com/store

downloads:
  windows: https://github.com/Jimminer/open-eclass-companion/releases/download/test/windows.txt
  android: https://github.com/Jimminer/open-eclass-companion/releases/download/test/android.txt
  test: /assets/favicon.ico

show_links: true
show_downloads: true

github:
  is_project_page: false