theme: jekyll-theme-cayman

title: Open eClass Companion App
description: Made by Dimitris Gkoumas

links:
  githubprof: https://github.com/Jimminer
  playstore: https://play.google.com/store

downloads:
  windows: https://raw.githubusercontent.com/Jimminer/open-eclass-companion/main/windows/test
  android: https://raw.githubusercontent.com/Jimminer/open-eclass-companion/main/android/test

show_links: true
show_downloads: true

github:
  is_project_page: false